#Lotto Analysis by Gwen Virtue
#Takes a lottery ticket generated by lottery.py class, and compares it to a newly generated lotto ticket.
#The script will continue creating new numbers until a match for the lotto ticket is found. 
#Eventually it will return how many tries it took to find the winning ticket. Could take a while.

from random import randint
import lottery

lotto = lottery.Lottery()


my_ticket = []
test_ticket = lotto.winner


for i in range(4):
	my_ticket.append(randint(1,10))

def compare(my_ticket, test_ticket):
	if len(my_ticket) != len(test_ticket):
		return False

	my_ticket.sort()
	test_ticket.sort()

	ticket_found = 0
	num_tries = 0

	while(ticket_found == 0):
		if my_ticket == test_ticket:
			ticket_found = 1
			return num_tries
		else:
			lotto.generate_winner()
			test_ticket = lotto.winner
			num_tries += 1

print(f"It took {compare(my_ticket, test_ticket)} times to find your winning ticket. Better off playing the stock market.")
